  version: '3'
  services:
    mysql:
      image: 'mysql:8'
      ports:
        - '3306:3306'
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=hellodemo
        - MYSQL_USER=hellouser
        - MYSQL_PASSWORD=secret
